### ISSUE TITLE
Broadwell core M

### ISSUE THREAD

**Issue by anerik70** [Piker-Alpha/ssdtPRGen.sh#198]
How can I solve this?
<img width="776" alt="captura de pantalla 2016-02-20 a las 1 28 51 p m" src="https://cloud.githubusercontent.com/assets/5209138/13204240/baf23902-d898-11e5-98ab-b5c2c25b9553.png">

**Comment by Piker-Alpha** [comment]
1.) The board-id error is fixed in ssdtPRGen.sh v17.8 (thank you for reporting it here).
2.) Open Mac-BE0E8AC46FE800CC.plist and change 2400 into 2000 under Frequencies (Item-0)
3.) Change "0d000000" into "08000000" under FrequencyVectors (Item-0).
4.) Change "18000000 01000000" into "14000000 01000000" under FrequencyVectors (Item-0) (see notes).
5.) Save your changes and re-run ssdtPRGen.sh

Notes:
1.) You can use ALT+SHIFT-RIGHT on a Windows keyboard to locate "18000000 01000000" under FrequencyVectors (Item-0),
2.) The value 18000000 (24 decimal) is the maximum turbo frequency (you want 14000000 for your processor).

**Comment by anerik70** [comment]
Thank you for answer. I followed your steps. The ssdt generates without issues now, but when i reboot it results in kernel panic. See attach
![12782151_816108708535606_1567648871_n](https://cloud.githubusercontent.com/assets/5209138/13218751/95adc048-d939-11e5-9c29-716f80da7b05.jpg)

**Comment by Piker-Alpha** [comment]
Can you please confirm that the error is fixed in v17.8?

Restore the plist and redo steps 2-4 and 5, but now once at a time. This should help us to catch the error (when it triggers the KP).

**Comment by anerik70** [comment]
I can confirm that the error is fixed and that the ssdt generates without errors. But when i try to boot with the generated ssdt i get kernel pAnic. I tried with every single step and got kernel panic. I'm grateful with your help.

**Comment by Piker-Alpha** [comment]
Ok. Thanks (for the confirmation).

I asked someone else to do the same and it works. Perhaps your KP is triggered by something else. Feel free to e-mail me (see script source) the plist so that I can have a look at it.

**Comment by anerik70** [comment]
Here is my plist. Thank you for your support.

[config.plist.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/141337/config.plist.zip)

**Comment by anerik70** [comment]
Hi! I can confirm it is working now! I had to delete some parameters from SMBIOS. Now PM is working fine. Thaaaaaaaank You Piker
<img width="1055" alt="captura de pantalla 2016-02-22 a las 5 19 43 p m" src="https://cloud.githubusercontent.com/assets/5209138/13238360/58c0addc-d9a0-11e5-8268-07ee01689d7e.png">
![Uploading Captura de pantalla 2016-02-22 a las 5.23.59 p.m..png…]()
![Uploading Captura de pantalla 2016-02-22 a las 5.27.51 p.m..png…]()
![Uploading Captura de pantalla 2016-02-22 a las 5.33.50 p.m..png…]()

**Comment by Piker-Alpha** [comment]
Please upload your new/modified config.plist so that other people can see what they can do. Thanks!

**Comment by anerik70** [comment]
I have to delete Board ID in SMBIOS to avoid kernel panic but i notice that clover auto inject Mac-189A3D4F975D5FFC so i think it is not fixed yet. Mac-BE0E8AC46FE800CC is the problem.
<img width="963" alt="captura de pantalla 2016-02-22 a las 11 35 30 p m" src="https://cloud.githubusercontent.com/assets/5209138/13241878/337adba2-d9bd-11e5-8798-3c1e43f2d96d.png">

**Comment by Piker-Alpha** [comment]
Ok so Mac-189A3D4F975D5FFC.plist is working for your setup and Mac-BE0E8AC46FE800CC.plist may be a problem, or the modifications you made in it, but let us check that first.

1.) Backup Mac-189A3D4F975D5FFC.plist in the resource directory.
2.) Replace Mac-189A3D4F975D5FFC.plist with Mac-BE0E8AC46FE800CC.plist
3.) Reboot with -f and see if you can boot without the KP.

Another thing. When I asked for your modded plist I wasn't talking about config.plist but Mac-BE0E8AC46FE800CC.plist which I asked you to modify (so that I can check it for errors).

**Comment by anerik70** [comment]
Thanks for answer. Replacing Mac-189A3D4F975D5FFC.plist with Mac-BE0E8AC46FE800CC.plist results in kernel panic.

About plist it was my mistake here is the request plist
[Mac-BE0E8AC46FE800CC.plist.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/143053/Mac-BE0E8AC46FE800CC.plist.zip)

**Comment by Piker-Alpha** [comment]
Ok, but did you use the modified plist or the factory vanilla one? If you used the modified one, then try the factory vanilla one.

I also noticed, in the modified plist, that you forgot to change 2400 under Frequencies into 2000. CPUFloor is also 1000 but yours should be set to 500.

**Comment by anerik70** [comment]
I used the modified

**Comment by anerik70** [comment]
Hi Piker!
I want to thank you for your help and your time.
This is what I did today:

A.
0.) Restore factory vanilla Mac-BE0E8AC46FE800CC.plist
1.) Backup Mac-189A3D4F975D5FFC.plist in the resource directory.
2.) Replace Mac-189A3D4F975D5FFC.plist with Mac-BE0E8AC46FE800CC.plist
3.) Reboot with -f.
Result: Kernel Panic

B.
0.) Restore factory vanilla Mac-BE0E8AC46FE800CC.plist
1.) I re-edit the Mac-BE0E8AC46FE800CC.plist with correct CPUFloor (500) and change 2400 under Frequencies into 2000, Change "0d000000" into "08000000" under FrequencyVectors (Item-0) and Change "18000000 01000000" into "14000000 01000000" under FrequencyVectors (Item-0).
2.) Backup Mac-189A3D4F975D5FFC.plist in the resource directory.
3.) Replace Mac-189A3D4F975D5FFC.plist with Mac-BE0E8AC46FE800CC.plist
4.) Reboot with -f.
Result: Success! (See attach).

C.
0.) Restore factory vanilla Mac-BE0E8AC46FE800CC.plist
1.) I re-edit the Mac-BE0E8AC46FE800CC.plist with correct CPUFloor (500) and change 2400 under Frequencies into 2000, Change "0d000000" into "08000000" under FrequencyVectors (Item-0) and Change "18000000 01000000" into "14000000 01000000" under FrequencyVectors (Item-0).
2.) Restore Mac-189A3D4F975D5FFC.plist in the resource directory.
3.) Reboot with -f.
Result: Kernel Panic.

Conclusion: THE PROBLEM IS Mac-BE0E8AC46FE800CC.plist.

Thank you very much Piker. Now i'm on the correct way.
<img width="906" alt="captura de pantalla 2016-02-24 a las 6 18 31 a m" src="https://cloud.githubusercontent.com/assets/5209138/13285596/87e29f7e-dac9-11e5-94ea-527967a0eb5a.png">
<img width="1366" alt="proof" src="https://cloud.githubusercontent.com/assets/5209138/13285598/8d37cc56-dac9-11e5-86c3-1d28bffa840d.png">

**Comment by Piker-Alpha** [comment]
Good work! And sure. You cannot use the unmodified Mac-BE0E8AC46FE800CC.plist (procedure A) but I don't understand why you need to replace Mac-189A3D4F975D5FFC.plist with a modified copy of Mac-BE0E8AC46FE800CC.plist since your are using Mac-BE0E8AC46FE800CC as board-id. Like it is still using it, but perhaps this is (was?) kernel cache related?

Also. You now changed the CPUFloor from 1000 to 500 (which is good) but you should also change "0d000000" into "05000000" (sorry, my mistake) under FrequencyVectors (Item-0) so that it will step down to 500 MHz. Right now that is not working.

**Comment by anerik70** [comment]
Good work Piker! Thank you! Thank you! Thank you lord! I'll do the changes and report soon.

**Comment by anerik70** [comment]
I did the changes but CPUFloor still is 800MHz

**Comment by Piker-Alpha** [comment]
AppleIntelInfo.kext will filter out everything below 800 MHz so we need to fix this in the source code:

https://github.com/Piker-Alpha/AppleIntelInfo/blob/master/AppleIntelInfo/AppleIntelInfo.cpp#L282

Change the 8 into 5 (in two places) and compile the kext yourself. That should work.

And the Intel Power Gadget may be too slow to even detect it.

**Comment by anerik70** [comment]
Sorry, I don't have XCODE. Can you compile it for me?

**Comment by anerik70** [comment]
It seen to reach the Floor when is sleeping
<img width="1054" alt="captura de pantalla 2016-02-25 a las 8 07 14 a m" src="https://cloud.githubusercontent.com/assets/5209138/13320513/8f513148-db97-11e5-86ea-71826ad7d96c.png">

**Comment by Piker-Alpha** [comment]
Xcode is a free download (only requires registration) and I usually do not share compiled binaries as there is nothing to learn from a simple download. 

The output looks fine to me.
