### ISSUE TITLE
i7 6700K, booting with generated SSDT.aml gives "Remote Disc" in finder.

### ISSUE THREAD

**Issue by Sander37** [Piker-Alpha/ssdtPRGen.sh#225]
Hi Pike,

First of all thanks for all the good info and tools.

I recently bought a new hack, Asus Z170 pro gaming with i7 6700K. Almost everything is working, except for AppleLPC not being loaded without an injector kext and CPU-Turbo.

To get PM fully working I tried ssdtPRGen.sh

the SSDT is generated without errors, 
When I boot with the ssdt in clover/acpi/patched/ , AppleIntelInfo.kext reports all power states are working. And IntelPower Gadget show a different behaviour of CPU freq an Power consumption.
Average CPU-freq an Power are both higher in idle when the ssdt is installed. I'm still experimenting with BIOS CPU settings to get better results.

But the strangest thing is:
"Remote Disc" appears in finder.
After removing the SSDT and rebooting, the remote disc is gone.

Do you have any idea what could cause the remote disc to appear?

grtz,
Sander.

[ssdt.dsl.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/305826/ssdt.dsl.zip)

**Comment by Piker-Alpha** [comment]
Hi. Sorry, but I can't do much without data/info. I would first need the output of AppleIntelInfo.kext (with and without the generated SSDT) and two images of the Intel Power Gadget showing the difference.

**Comment by Sander37** [comment]
See attached the requested info.
IPG screenshots made during idle ( only IntelPowerGadget running.)
and during a CineBench openGL testrun.

I also included an IOregistryExplorerv2.1 dump, just in case...

[noSSDT_reports.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/310183/noSSDT_reports.zip)
[withSSDT_reports.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/310184/withSSDT_reports.zip)

and:

Jun  3 13:56:47 localhost kernel[0]: cpuid_fn(0x00000006) eax:0x000027f7 ebx:0x00000002 ecx:0x00000001 edx:0x00000000
Jun  3 13:56:47 localhost kernel[0]: cpuid_fn(0x00000006) eax:0x000027f7 ebx:0x00000002 ecx:0x00000009 edx:0x00000000

**Comment by Piker-Alpha** [comment]
Ok. Thank you for the files. Now I can explain what is going on. First. The generated SSDT sets a property called: "plugin-type" with a value of 1 (one) and the required drivers, like X86PlatformShim and IOPlatformEnabler, are properly loaded.

One of the things that you may have noticed is this difference:

IA32_ENERGY_PERF_BIAS......(0x1B0) : 0xF (without SSDT)
IA32_ENERGY_PERF_BIAS......(0x1B0) : 0x1 (with SSDT)

A rather important one, because the first (higher) value is used for notebooks and the second (lower) value for desktop PC's like the iMac. The higher the value (max 15) the less responsive the hardware will be (to extend the battery life) and the lower the value is (min 1) the quicker it will react (on AC power) but it will (of course) also draw a bit more power. If you don't like that, then use: https://github.com/Piker-Alpha/freqVectorsEdit.sh to copy the FrequencyVectors from some notebook.

The Remote Disc option in the Finder appears as a result of ApplePlatformEnabler being loaded. Take a look at the properties like DVDSupported (boolean True) and ODSSupported (boolean True).

Now you know why, and everything is fine. As Apple and Intel had in mind for our hardware. In short. Nothing has to be done. just keep using that SSDT ;)

**Comment by Sander37** [comment]
Thanks for the explanation,

To be honest, I didn't spot the Energy_Perf_Bias, but that explains a lot. ;)

I'll see if I can get the remote disc to disappear, and will get back on that.

**Comment by Piker-Alpha** [comment]
See Finder Preferences (devices) where you can hide it (along with CD's and iPod's).

**Comment by Sander37** [comment]
Removing it from the sidebar is one thing, but I would prefer not to see it in my iMac/ at all.

It shouldn't be there, right? I don't have a remote disc.
Or is it there, because i don't have a local DVD-drive? 

indeed both booleans are TRUE in ioreg, are they supposed to be TRUE?

Could I make them FALSE with an ApplePlatformEnabler.kext patch?
edit: No...that's doesn't seem to be the way ;)

I found a working option:
sudo defaults write /Library/Preferences/com.apple.NetworkBrowser EnableODiskBrowsing -bool false; killall Finder

**Comment by Piker-Alpha** [comment]
Cool, so we can close this issue?

**Comment by Sander37** [comment]
Yes, 
thank you!
