### ISSUE TITLE
6770K on Sierra

### ISSUE THREAD

**Issue by dmeadows013** [Piker-Alpha/ssdtPRGen.sh#280]
When trying to generate an SSDT for my overclocked 6770K on 10.12, I ran into several issues due to board compatibility and CPU type. Here is my output for the ./ssdtPRGen.sh:

```
iMac:~ dmeadows$ sudo ./ssdtPRGen.sh 


ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
             v20.4 Copyright (c) 2013-2016 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.12 (16A323)
Brandstring: "Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz"

Version: models.cfg v160 / Skylake.cfg v193


Scope (_PR_) {222 bytes} with ACPI Processor declarations found in DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'iMac14,2' with board-id [Mac-27ADBB7B4CEE8E61]
Skylake Core i7-6700K processor [0x506E3] setup [0x0705]
With a maximum TDP of 91 Watt, as specified by Intel
Number logical CPU's: 8 (Core Frequency: 4000 MHz)
Number of Turbo States: 2 (4100-4200 MHz)
Number of P-States: 35 (800-4200 MHz)
Injected C-States for CPU0 (C1,C3,C6,C7,C8,C9,C10)
Injected C-States for CPU1 (C1,C2,C3,C6,C7)
Warning: 'cpu-type' may be set improperly (0x0705 instead of 0x0905)
     - Clover users should read https://clover-wiki.zetam.org/Configuration/CPU#cpu_type
Error: board-id [Mac-27ADBB7B4CEE8E61] not supported by Skylake – check SMBIOS data / use the -target option

Do you want to continue (y/n)?
```

I also tried specifying target, but got a similar result:

```
iMac:~ dmeadows$ sudo ~/ssdtPRGen.sh -b Mac-27ADBB7B4CEE8E61 -m iMac14,2 -target 4


ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
             v20.4 Copyright (c) 2013-2016 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.12 (16A323)
Brandstring: "Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz"

Override value: (-b) board-id, now using: Mac-27ADBB7B4CEE8E61!
Override value: (-m) model, now using: iMac14,2!
Override value: (-target) CPU, now using: Skylake!

Version: models.cfg v160 / Skylake.cfg v193


Scope (_PR_) {222 bytes} with ACPI Processor declarations found in DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'iMac14,2' with board-id [Mac-27ADBB7B4CEE8E61]
Skylake Core i7-6700K processor [0x506E3] setup [0x0705]
With a maximum TDP of 91 Watt, as specified by Intel
Number logical CPU's: 8 (Core Frequency: 4000 MHz)
Number of Turbo States: 2 (4100-4200 MHz)
Number of P-States: 35 (800-4200 MHz)
Injected C-States for CPU0 (C1,C3,C6,C7,C8,C9,C10)
Injected C-States for CPU1 (C1,C2,C3,C6,C7)
Warning: 'cpu-type' may be set improperly (0x0705 instead of 0x0905)
     - Clover users should read https://clover-wiki.zetam.org/Configuration/CPU#cpu_type
Error: board-id [Mac-27ADBB7B4CEE8E61] not supported by Skylake – check SMBIOS data / use the -target option

Do you want to continue (y/n)? 
```

Will these errors affect the SSDT.aml generated? If so, how can I get past them?

**Comment by Piker-Alpha** [comment]
You may ignore the warning about the cpu-type, but the Haswell iMac14,2 SMBIOS data and the Mac-27ADBB7B4CEE8E61 board-id should not be used with a Skylake processors.

**Comment by mfdphd** [comment]
Hello, Piker-Alpha

I have a similar issue, should I use. I am using a Skylake. Thank you for your help.



MDs-iMac:~ md-sierra$ curl -o ~/ssdtPRGen.sh https://raw.githubusercontent.com/Piker-Alpha/ssdtPRGen.sh/Beta/ssdtPRGen.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  153k  100  153k    0     0   320k      0 --:--:-- --:--:-- --:--:--  320k
MDs-iMac:~ md-sierra$ chmod +x ~/ssdtPRGen.sh
MDs-iMac:~ md-sierra$ sudo ~/ssdtPRGen.sh
Password:


ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
             v21.4 Copyright (c) 2013-2017 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <
/Users/md-sierra/ssdtPRGen.sh: line 3862: /Users/md-sierra/Library/ssdtPRGen/Data/Versions.cfg: No such file or directory

System information: Mac OS X 10.12.3 (16D32)
Brandstring: "Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz"

Notice: Downloading extractACPITables.zip ...
Notice: Downloading User Defined.cfg ...
Notice: Downloading Sandy Bridge.cfg ...
Notice: Downloading Ivy Bridge.cfg ...
Notice: Downloading Haswell.cfg ...
Notice: Downloading Broadwell.cfg ...
Notice: Downloading Skylake.cfg ...
Version: models.cfg v160 / Skylake.cfg v193


Scope (_PR_) {222 bytes} with ACPI Processor declarations found in DSDT (ACPI 1.0 compliant)
Notice: Downloading Restrictions.cfg ...
Generating ssdt.dsl for a 'iMac14,2' with board-id [Mac-27ADBB7B4CEE8E61]
Skylake Core i7-6700K processor [0x506E3] setup [0x0705]
With a maximum TDP of 91 Watt, as specified by Intel
Number logical CPU's: 8 (Core Frequency: 4000 MHz)
Number of Turbo States: 2 (4100-4200 MHz)
Number of P-States: 35 (800-4200 MHz)
Injected C-States for CPU0 (C1,C3,C6,C7,C8,C9,C10)
Injected C-States for CPU1 (C1,C2,C3,C6,C7)
Warning: 'cpu-type' may be set improperly (0x0705 instead of 0x0905)
	 - Clover users should read https://clover-wiki.zetam.org/Configuration/CPU#cpu_type
Error: board-id [Mac-27ADBB7B4CEE8E61] not supported by Skylake – check SMBIOS data / use the -target option

Do you want to continue (y/n)? y
Warning: 'system-type' may be set improperly (1 instead of 2)
	 - Clover users should read https://clover-wiki.zetam.org/Configuration/ACPI#acpi_smartupsNotice: Downloading iasl.zip ...

Compiling: ssdt_pr.dsl
Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Users/md-sierra/Library/ssdtPRGen/ssdt.dsl - 364 lines, 11348 bytes, 73 keywords
AML Output:    /Users/md-sierra/Library/ssdtPRGen/ssdt.aml - 2389 bytes, 28 named objects, 45 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations
Do you want to open ssdt.dsl (y/n)? y

**Comment by aeroxy** [comment]
`You may ignore the warning about the cpu-type, but the Haswell iMac14,2 SMBIOS data and the Mac-27ADBB7B4CEE8E61 board-id should not be used with a Skylake processors.`

@Piker-Alpha but I have to use iMac14,2 SMBIOS to get my GPU (GTX980 4GB) to work, otherwise it will boot into black screen...(which means iMac17,1 or Mac Pro 6,1 are not going to work with GTX980 4GB).
